### ISSUE TITLE
RevIN is not suitable for pEMS data sets

### ISSUE THREAD

**Issue by wengwenchao123** [cure-lab/SCINet#23]
Hello:  
I have tried to use RevIN on perMS data set, the result is far worse than without RevIN, may I ask whether your test result is the same

**Comment by wengwenchao123** [comment]
> Hello: I have tried to use RevIN on perMS data set, the result is far worse than without RevIN, may I ask whether your test result is the same
It's using the hyperparameters that you give it

**Comment by VEWOXIC** [comment]
We did try the RevIN on the pems dataset and found it did hurt the performance. We presume that it is because the distribution for the training and testing set of PEMS is identical. You can use the tool provided in `./utils/histogram.ipynb` to verify the distribution. We recommend enabling RevIN when these two distribution is remarkably different. 
Thanks for your attention!

**Comment by Obliman** [comment]
Is there another name for RevIN, or a definition in the paper? I have not found anything from Google searches.

**Comment by liuaoy** [comment]
> 

可能是中继监督
